# Playspot Standalone Scratch
#
# VERSION 1.0.0

FROM arm32v7/node:8
MAINTAINER Van Simmons <van.simmons@computecycles.com>

RUN mkdir -p /scratch-vm
WORKDIR /scratch-vm
COPY ./package-lock.json /scratch-vm
COPY ./package.json /scratch-vm
COPY ./src /scratch-vm/src
RUN npm install || true
VOLUME /scratch-vm/game

ENTRYPOINT ["node", "/scratch-vm/src/index.js"]

