# Playspot Standalone Scratch
#
# VERSION 1.0.0

FROM arm32v7/node:8
MAINTAINER Van Simmons <van.simmons@computecycles.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app/
COPY ./ /usr/src/app/
RUN npm install || true

EXPOSE 80

ENTRYPOINT ["node", "/src/index.js"]

